/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Books.gltf --transform 
Files: Books.gltf [71.05MB] > /Users/andrijagajic/Downloads/books/Books-transformed.glb [1.02MB] (99%)
Author: local.yany (https://sketchfab.com/local.yany)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/books-1e2bbf1cd0304e66a93b95588731994b
Title: books
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./img/Books-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.EvB1_Hbacks1Shape_page_edges_0.geometry} material={materials.page_edges} position={[0.11, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.EvB1_Hbacks1Shape_cover_0.geometry} material={materials.cover} position={[0.11, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.EvB1_Hbacks1Shape_cover_jacket_0.geometry} material={materials.cover_jacket} position={[0.11, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.EvB1_Hbacks2Shape_cover_0.geometry} material={materials.cover_0} position={[0.195, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.EvB1Lbooks1Shape_cover_0.geometry} material={materials.cover_1} position={[0.511, 0, 0.05]} scale={0.01} />
      <mesh geometry={nodes.EvB1Lbooks1Shape_cover_inner_0.geometry} material={materials.cover_inner} position={[0.511, 0, 0.05]} scale={0.01} />
      <mesh geometry={nodes.EvB1Lbooks1Shape_cover_jacket1_0.geometry} material={materials.cover_jacket1} position={[0.511, 0, 0.05]} scale={0.01} />
      <mesh geometry={nodes.EvB1Lbooks1Shape_cover_jacket2_0.geometry} material={materials.cover_jacket2} position={[0.511, 0, 0.05]} scale={0.01} />
      <mesh geometry={nodes.EvB1Lbooks2Shape_cover_0.geometry} material={materials.cover_2} position={[0.729, 0, 0.049]} scale={0.01} />
      <mesh geometry={nodes.EvB1Lbooks2Shape_cover_inner_0.geometry} material={materials.cover_inner_0} position={[0.729, 0, 0.049]} scale={0.01} />
      <mesh geometry={nodes.EvB1Lbooks2Shape_cover_jacket1_0.geometry} material={materials.cover_jacket1_0} position={[0.729, 0, 0.049]} scale={0.01} />
      <mesh geometry={nodes.EvB1_Pbacks1Shape_cover_0.geometry} material={materials.cover_3} position={[-0.18, 0, -0.009]} scale={0.01} />
      <mesh geometry={nodes.EvB1_Pbacks2Shape_cover_0.geometry} material={materials.cover_4} position={[0.419, 0.088, 0.047]} rotation={[0, -0.027, Math.PI / 2]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/Books-transformed.glb')
