/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ForestDiorama.gltf --transform 
Files: ForestDiorama.gltf [81.92MB] > /Users/andrijagajic/Downloads/forest-sided_a_peaceful_place_to_live_diorama/ForestDiorama-transformed.glb [7.33MB] (91%)
Author: Cleuza Costa (https://sketchfab.com/CleuzaCosta)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/forest-sided-a-peaceful-place-to-live-diorama-01bde51946244b9db917bf9370ef605b
Title: Forest-sided, a peaceful place to live: Diorama
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./img/ForestDiorama-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.DIORAMAgroundplanepolySurface366_aiStandardSurface8_0.geometry} material={materials.aiStandardSurface8} position={[0, -399.043, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.879} />
      <mesh geometry={nodes.DIORAMAgroundplanepolySurface372_aiStandardSurface7_0.geometry} material={materials.aiStandardSurface7} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.DIORAMAgroundplanepolySurface389_aiStandardSurface6_0.geometry} material={materials.aiStandardSurface6} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.DIORAMAgroundplanepolySurface393_T_Groundplane_BC_01_0.geometry} material={materials.T_Groundplane_BC_01} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.DIORAMAgroundplanepolySurface386_T_Groundplane_BC_0_0.geometry} material={materials.T_Groundplane_BC_0} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.DIORAMAgroundplanepolySurface392_aiStandardSurface9_0.geometry} material={materials.aiStandardSurface9} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.DIORAMAgroundplanepolySurface383_T_Groundplane_BC_07_0.geometry} material={materials.T_Groundplane_BC_07} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.DIORAMAgroundplaneFrame_01_geo_DIORAMAgroundplaneaiStandardSurface18_0.geometry} material={materials.DIORAMAgroundplaneaiStandardSurface18} position={[0, -240.469, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.908} />
      <mesh geometry={nodes.DIORAMAgroundplaneWater_01_geo_T_Water_BC_01_0.geometry} material={materials.T_Water_BC_01} position={[0, -212.273, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.879} />
      <mesh geometry={nodes.Birch_01_grp1_Trunk_01_geo_T_Tree_BC_01_0.geometry} material={materials.T_Tree_BC_01} />
      <mesh geometry={nodes.RedOak_01_grp_Trunk_02_geo_T_Tree_BC_02_0.geometry} material={materials.T_Tree_BC_02} />
      <mesh geometry={nodes.Balcony_01_geo_T_Balcony_BC_01_0.geometry} material={materials.T_Balcony_BC_01} position={[-298.49, 864.676, 27.354]} rotation={[0, -0.216, 0]} />
      <mesh geometry={nodes.Exterior_01_geo_T_EcoBuldings_BC_01_0.geometry} material={materials.T_EcoBuldings_BC_01} position={[-298.49, 864.676, 27.354]} rotation={[0, -0.216, 0]} />
      <mesh geometry={nodes.Side_01_geo_aiStandardSurface15_0.geometry} material={materials.aiStandardSurface15} position={[-298.49, 864.676, 27.354]} rotation={[0, -0.216, 0]} />
      <mesh geometry={nodes.Door_01_geo_T_Door_01_BC_01_0.geometry} material={materials.T_Door_01_BC_01} position={[879.362, 458.749, 662.155]} rotation={[0, -1.203, 0]} />
      <mesh geometry={nodes.SolarPanel_01_geo_T_SolarPanel_BC_01_0.geometry} material={materials.T_SolarPanel_BC_01} position={[-712.521, 1327.007, -307.169]} rotation={[0, -0.251, 0]} scale={1.009} />
      <mesh geometry={nodes.DogHouse_01_geo_T_DogHouse_BC_01_0.geometry} material={materials.T_DogHouse_BC_01} position={[-728.847, 928.096, -833.51]} rotation={[-Math.PI, -0.93, -Math.PI]} scale={0.966} />
      <mesh geometry={nodes.Couch_01_geo_T_Couch_BC_01_0.geometry} material={materials.T_Couch_BC_01} position={[-498.438, 887.677, 235.511]} />
      <mesh geometry={nodes.polySurface2_T_Pillows_BC_01_0.geometry} material={materials.T_Pillows_BC_01} position={[1016.901, 1115.489, -399.931]} />
      <mesh geometry={nodes.polySurface1_aiStandardSurface18_0.geometry} material={materials.aiStandardSurface18} position={[1085.787, 1113.874, -365.806]} rotation={[-0.135, -0.924, 0.001]} scale={1.161} />
      <mesh geometry={nodes.polySurface1_aiStandardSurface19_0.geometry} material={materials.aiStandardSurface19} position={[1119.635, 1115.489, -296.346]} rotation={[-0.141, -0.955, -0.006]} scale={1.161} />
      <mesh geometry={nodes.Scooter_01_geo_T_Scooter_BC_01_0.geometry} material={materials.T_Scooter_BC_01} position={[-279.314, 968.638, -724.138]} rotation={[0.291, 1.26, -0.285]} scale={1.281} />
      <mesh geometry={nodes.ClothesLine_01_geo_T_ClothesLine_BC_02_0.geometry} material={materials.T_ClothesLine_BC_02} position={[-163.268, 886.251, 448.776]} rotation={[-Math.PI, -0.951, -Math.PI]} />
      <mesh geometry={nodes.Vases_01_geo_aiStandardSurface21_0.geometry} material={materials.aiStandardSurface21} />
      <mesh geometry={nodes.Vases_01_geo_T_Vases_BC_01_0.geometry} material={materials.T_Vases_BC_01} />
      <mesh geometry={nodes.Vases_01_geo_aiStandardSurface22_0.geometry} material={materials.aiStandardSurface22} />
      <mesh geometry={nodes.Prop_CanoeCanoe_01_geo_Prop_CanoeT_Canoe_BC_01_0.geometry} material={materials.Prop_CanoeT_Canoe_BC_01} position={[-784.468, 0, 1538.384]} />
      <mesh geometry={nodes.polySurface396_T_GardeningTools_BC_01_0.geometry} material={materials.T_GardeningTools_BC_01} position={[243.191, 478.498, 544.727]} />
      <mesh geometry={nodes.Guitar_01_geo_T_Guitar_BC_01_0.geometry} material={materials.T_Guitar_BC_01} position={[930.904, 1141.498, -287.149]} rotation={[1.943, -0.232, 2.609]} />
      <mesh geometry={nodes.SunUmbrella_01_geo_aiStandardSurface3T_SunUmbrella_BC_01_0.geometry} material={materials.aiStandardSurface3T_SunUmbrella_BC_01} position={[-597.16, 885.607, 343.419]} />
      <mesh geometry={nodes.Rocks_01_geo1_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} />
      <mesh geometry={nodes.WaterReserve_01_geo_T_WaterReserve_BC_01_0.geometry} material={materials.T_WaterReserve_BC_01} position={[991.718, 464.638, 290.455]} rotation={[-3.111, -0.013, -3.114]} />
      <mesh geometry={nodes.Deco_01_plane1_aiStandardSurface25_0.geometry} material={materials.aiStandardSurface25} />
      <mesh geometry={nodes.Deco_01_plane1_T_Deco_01_0.geometry} material={materials.T_Deco_01} />
      <mesh geometry={nodes.BirdHouse_01_geo_T_BirdHouse_BC_02_0.geometry} material={materials.T_BirdHouse_BC_02} position={[-101.496, 0, 1766.986]} rotation={[0, -0.362, 0]} />
      <mesh geometry={nodes.birdhouseBirdHouse_01_geo_birdhouseT_BirdHouse_BC_01_0.geometry} material={materials.birdhouseT_BirdHouse_BC_01} position={[973.682, 1256.294, -157.791]} rotation={[0, -0.362, 0]} />
      <mesh geometry={nodes.Windows_plane_01_aiStandardSurface28_0.geometry} material={materials.aiStandardSurface28} />
      <mesh geometry={nodes.Windows_Interior_plane_01_T_Windows_BC_01_0.geometry} material={materials.T_Windows_BC_01} />
      <mesh geometry={nodes.Vegetation_01_plane_T_Plants_0.geometry} material={materials.T_Plants} />
      <mesh geometry={nodes.Lamp_01_geo2_T_Lamp_BC_01_0.geometry} material={materials.T_Lamp_BC_01} />
      <mesh geometry={nodes.TreeHouse_01_geo_T_TreeHouse_BC_01_0.geometry} material={materials.T_TreeHouse_BC_01} />
      <mesh geometry={nodes.Rope_01_geo_aiStandardSurface16_0.geometry} material={materials.aiStandardSurface16} />
      <mesh geometry={nodes.Rope_01_geo_aiStandardSurface17_0.geometry} material={materials.aiStandardSurface17} />
      <mesh geometry={nodes.GreenHouse_01_grp1_aiStandardSurface30_0.geometry} material={materials.aiStandardSurface30} />
      <mesh geometry={nodes.GardeningTable_01_geo1_T_GardeningTable_BC_01_0.geometry} material={materials.T_GardeningTable_BC_01} />
    </group>
  )
}

useGLTF.preload('/ForestDiorama-transformed.glb')
