/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 macbookpro.gltf --transform 
Files: macbookpro.gltf [2.86MB] > /Users/andrijagajic/Downloads/apple_macbook_pro_16_inch_2021/macbookpro-transformed.glb [242.12KB] (92%)
Author: jc1245 (https://sketchfab.com/jasperchui2007)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-macbook-pro-16-inch-2021-6a42b31bac064b00a91fbfebec07c852
Title: Apple MacBook Pro 16 inch 2021
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./img/macbookpro-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.PaletteMaterial003} position={[0, 0.1, -1.012]} rotation={[-1.925, 0, 0]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials['Material.008']} position={[0, 0.1, -1.012]} rotation={[-1.925, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/macbookpro-transformed.glb')
