/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 retropiano.gltf --transform 
Files: retropiano.gltf [13.83MB] > /Users/andrijagajic/Downloads/retro_piano/retropiano-transformed.glb [384.92KB] (97%)
Author: DailyArt (https://sketchfab.com/D.art)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/retro-piano-fd4971cd71564319aa2132266d208185
Title: Retro piano
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./img/retropiano-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_6.geometry} material={materials.gangqin} position={[-1037.188, 345.494, -158.323]} scale={1081.167} />
    </group>
  )
}

useGLTF.preload('/retropiano-transformed.glb')
