/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 RetroLibrary.gltf --transform 
Files: RetroLibrary.gltf [7.16MB] > /Users/andrijagajic/Downloads/retro_library_diorama/RetroLibrary-transformed.glb [985.84KB] (86%)
Author: justin112358 (https://sketchfab.com/justin112358)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-library-diorama-2bea4c3f87414140962e84e79a49a836
Title: Retro Library Diorama
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./img/RetroLibrary-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_3.geometry} material={materials.m_carpet} position={[-125, -10, 125]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.m_plant} position={[-125, -10, 125]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.m_walls} position={[-125, -10, 125]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.temp} position={[-125, -10, 125]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.m_blinds} position={[-125, -10, 125]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.m_books} position={[-125, -10, 125]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.m_chairs} position={[-125, -10, 125]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.m_computer} position={[-125, -10, 125]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.m_dark} position={[-125, -10, 125]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.m_shelves} position={[-125, -10, 125]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.m_table} position={[-125, -10, 125]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/RetroLibrary-transformed.glb')
